<a href="https://colab.research.google.com/github/tanishas05/ML-and-GenAI-with-Python-2026/blob/main/TanishaSharma_20201012025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import accuracy_score, confusion_matrix

In [67]:
df = pd.read_csv("Dataset 2.csv")

In [68]:
#q1
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [69]:
#q2
print("Rows and Columns:", df.shape)

Rows and Columns: (750, 10)

In [70]:
#q3
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [71]:
#q4
print("Numerical Features:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Features:")
print(df.select_dtypes(include=['object']).columns)

Numerical Features:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Features:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [72]:
#q5
print(df.isnull().sum())

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [73]:
#q6
print("Average Age:", df['Age'].mean())

Average Age: 41.824

In [74]:
#q7
print("Average Watch Hours:", df['WatchHoursPerWeek'].mean())

Average Watch Hours: 14.236

In [75]:
#q8
print("Average Monthly Spend:", df['MonthlySpend'].mean())

Average Monthly Spend: 689.9053333333334

In [76]:
#q9
print(df['SubscriptionType'].value_counts())

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [77]:
#q10
renewed_percentage = (df['SubscriptionRenewed'] == 'Yes').mean() * 100

print("Renewed Percentage:", renewed_percentage)

Renewed Percentage: 46.266666666666666

In [78]:
#q11
df_encoded = df.copy()

encoder = LabelEncoder()

for col in df_encoded.select_dtypes(include='object').columns:
    df_encoded[col] = encoder.fit_transform(df_encoded[col])

df_encoded.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [79]:
#q12
X = df_encoded.drop(['SubscriptionRenewed','UserID'], axis=1)

y = df_encoded['SubscriptionRenewed']

print(X.head())
print(y.head())

   Age  Gender  SubscriptionType  WatchHoursPerWeek  DevicesUsed  \
0   22       0                 0                 23            5
1   55       1                 0                  9            4
2   49       1                 0                  8            3
3   39       0                 1                 19            5
4   38       0                 1                 23            5

   FavoriteGenre  AdClicks  MonthlySpend
0              1        13           353
1              2        14           317
2              1        16           309
3              2        45           833
4              5        24           804
0    0
1    1
2    0
3    1
4    1
Name: SubscriptionRenewed, dtype: int64

In [80]:
#q13

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)

(600, 8)
(150, 8)

In [81]:
#q14
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [82]:
#q15
dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.56

In [83]:
#q16
cm = confusion_matrix(y_test, dt_pred)

print(cm)

[[48 34]
 [32 36]]

In [84]:
#q17
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

In [85]:
#q18
knn_accuracy = accuracy_score(y_test, knn_pred)

print("Decision Tree Accuracy:", dt_accuracy)
print("KNN Accuracy:", knn_accuracy)

Decision Tree Accuracy: 0.56
KNN Accuracy: 0.6333333333333333

In [86]:
#q19
X_reg = df_encoded.drop(['MonthlySpend','UserID'], axis=1)

y_reg = df_encoded['MonthlySpend']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split( X_reg,y_reg,test_size=0.2,random_state=42)

lr_model = LinearRegression()

lr_model.fit(X_train_reg, y_train_reg)

LinearRegression()

In [87]:
#q20
new_user = [[ 25, 1, 2, 15, 3, 1, 10, 1]]
predicted_spend = lr_model.predict(new_user)
print("Predicted Monthly Spend:", predicted_spend[0])

Predicted Monthly Spend: 1317.8351945433988

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [88]:
#Business Reflection Answers q1
feature_importance = pd.DataFrame({'Feature': X.columns,'Importance': dt_model.feature_importances_})

feature_importance.sort_values(by='Importance',ascending=False)

             Feature  Importance
7       MonthlySpend    0.218895
6           AdClicks    0.199287
0                Age    0.192702
3  WatchHoursPerWeek    0.170035
5      FavoriteGenre    0.085444
4        DevicesUsed    0.070835
1             Gender    0.047127
2   SubscriptionType    0.015675

Business Reflection Answers q2

Because the target has two categories:

Yes

No

Business Reflection Answers q3

Because MonthlySpend is a continuous numerical value.

In [89]:
#Business Reflection Answers q4
print("Decision Tree:", dt_accuracy)
print("KNN:", knn_accuracy)

Decision Tree: 0.56
KNN: 0.6333333333333333

Business Reflection Answers q5

*  Identify users likely to cancel.
*   Offer discounts and promotions.
*  Recommend personalized content.
*  Improve retention campaigns.